[general]
debug = True

[postgresql]
dbname = plants
user = plants_user
password = xxxxxxxx
host = localhost
port = 5432

[sensors]
dht_gpio = 4  # Remplacez par le numéro de GPIO utilisé
# nombre de capteurs miflora: 1 or 2
nbmi=2
# mi_mac = XX:XX:XX:XX:XX:XX  # Remplacez par l'adresse MAC de votre capteur MiFlora
# 5C:85:7E:12:E4:AE # 1
# 5C:85:7E:12:E5:06 # 2
# 5C:85:7E:13:41:EB # 3
# 5C:85:7E:13:3E:12 # 4
# 5C:85:7E:13:3C:48 # 5
mi_mac1 = 5C:85:7E:12:E5:06
mi_mac2 = 5C:85:7E:13:3E:12
