[postgresql]
dbname = plants
user = plants_user
password = Un2trois4
host = localhost
port = 5432

[sensors]
dht_gpio = 4  # Remplacez par le numéro de GPIO utilisé
# mi_mac = XX:XX:XX:XX:XX:XX  # Remplacez par l'adresse MAC de votre capteur MiFlora
mi_mac = 5C:85:7E:12:E5:06
